### ISSUE TITLE
in `to_specs': Could not find 'clocale' (>= 0) among 20 total gem(s) (Gem::LoadError)

### ISSUE THREAD

**Issue by emahuni** [avdv/clocale#22]
I am not sure what caused this, however, I can't use colorls or any other ruby gems that use this as a dependency. Initially it would tell me this:
```
Ignoring clocale-0.0.4 because its extensions are not built.  Try: gem pristine clocale --version 0.0.4
```
Then I ran the suggestion only to now get an incomplete build or something, which now causes everything that depends or touches any related dependencies to throw that exception:

```
System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'clocale' (>= 0) among 20 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/em/.gem/ruby/2.3.0:/Library/Ruby/Gems/2.3.0:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0', execute `gem env` for more information
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:1442:in `block in activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:1431:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:1431:in `activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:1413:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/colorls-1.1.1/exe/colorls:3:in `<top (required)>'
	from /usr/local/bin/colorls:22:in `load'
	from /usr/local/bin/colorls:22:in `<main>'
```

**Comment by avdv** [comment]
Hi, this could be caused by a broken/ misconfigured Ruby/rbenv installation. See the issue [here](https://github.com/athityakumar/colorls/issues/234), that might help.

Otherwise, paste the output of `gem install clocale`.

**Comment by emahuni** [comment]
thank you so much let me try it out and get back to you

**Comment by emahuni** [comment]
Ok I ended up doing this; I installed xcode-commandline-tools;

```sh
$ xcode-select --install
$ brew install rbenv
$ echo 'export PATH="/usr/local/opt/openssl/bin:$PATH"' >> ~/.zshrc
$ echo 'export LDFLAGS="-L/usr/local/opt/openssl/lib"' >> ~/.zshrc
$ echo 'export CPPFLAGS="-I/usr/local/opt/openssl/include"' >> ~/.zshrc
$ echo 'export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"' >> ~/.zshrc
$ sudo gem pristine --all #that produced a permissions error, but i don't care everything worked
$ sudo gem install colorls
```

I think all this was caused with the OS upgrade I did to Majove from previous Mac OS version. After doing this colorls is now working as before.

**Comment by rogerprz** [comment]
This worked for me: `sudo gem install colorls`
